<a href="https://colab.research.google.com/github/Olacherish/DataScienceClass/blob/main/PYTORCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MLP IMPLENENTATION IN SKLEARN/SCIKIT LEARN**

MLP IN SCIKIT LEARN

In [1]:
import sklearn

In [3]:
from sklearn import neural_network
from sklearn.neural_network import MLPClassifier as mlpClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [ ]:
data = load_breast_cancer
x = data.data
y = data.target

x_train, x_test = train_test_split( x, test_size=0.3, random_state=22)
y_train, y_test = train_test_split( y, test_size=0.3, random_state=22)

In [18]:
from sklearn.neural_network import MLPClassifier as mlpClassifier

mlp = mlpClassifier(
    learning_rate_init=0.01

    )

In [ ]:
mlp.fit(x_train, y_train)

## **IMPLEMENTING MLP USING PYTORCH**

In [ ]:
Pytorch was created by -> meta i.e facebook
Tensorflow -> Google

In [ ]:
from prompt_toolkit.formatted_text import OneStyleAndTextTuple
Pytorch is an open-source DL in AI

# key components
- Autograd: automatically compute gradients
- Pythonic: integrates seamlessly with python
- Tensor operation -> uses GPU accelerated

# Pytorch is used for:
- NN
- Computer vision
- NLP
- Reinforcement learning (RL)

# Why use PYtorch
- Flexibility
- Large community
- Efficient for training model
- Production Ready: TorchScript, OneStyleAndTextTuple
- Research friendly: academics


### **PYTORCH BASICS**

In [ ]:
# install pytorch as torch

In [7]:
!pip install torch

In [8]:
import torch

In [ ]:
# Tensors : are Core data structure in AI Model.
e.g google pixels

# Tensors are multi-dimensional arrays similar to NumPy
Arrays but with GPU support and Autograd capabilities

# Tensors are backbone of Pytorch operations

In [3]:
import torch

In [4]:
scalar = torch.tensor(7)
vector = torch.tensor([1, 2, 3])
matrix_2d = torch.tensor([
                    [1, 2, 3],
                    [4, 5, 6],
                    [5, 3, 2],
                    [7, 3, 4]
                    ])

In [23]:
print(f"Data type of scalar: {scalar.dtype}")
print(f"Data type of vector: {vector.dtype}")
print(f"Data type of matrix_2d: {matrix_2d.dtype}")

Data type of scalar: torch.int64
Data type of vector: torch.int64
Data type of matrix_2d: torch.int64


In [6]:
matric_2d = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


matric_2d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
matric_2d.shape

torch.Size([3, 3])

In [10]:
matric_2d.reshape(1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [5]:
torch.tensor

<function torch._VariableFunctionsClass.tensor>

In [ ]:
torch.matrix_2d

In [11]:
print(dir(matric_2d))

['H', 'T', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__dlpack__', '__dlpack_c_exchange_api__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__

In [13]:
torch.zeros

<function torch._VariableFunctionsClass.zeros>

In [15]:
tensor_1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

tensor_2 = torch.tensor([
                    [1, 2, 3],
                    [4, 5, 6],
                    [5, 3, 2],

                    ])

tensor_1 + tensor_2

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [12, 11, 11]])

In [16]:
tensor_1*tensor_2

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [35, 24, 18]])

In [17]:
tensor_1**tensor_2

tensor([[    1,     4,    27],
        [  256,  3125, 46656],
        [16807,   512,    81]])

In [18]:
print(type(tensor_1**tensor_2))

<class 'torch.Tensor'>


In [21]:
print(dir(tensor_1**tensor_2))

['H', 'T', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__dlpack__', '__dlpack_c_exchange_api__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__

In [ ]:
torch.cuda_is_available

In [24]:
print(torch.cuda.is_available())

True


In [25]:
# Create tensors
scalar = torch.tensor(5)                    # 0D tensor
vector = torch.tensor([1, 2, 3])           # 1D tensor
matrix = torch.tensor([[1, 2], [3, 4]])    # 2D tensor
random = torch.rand(2, 3)                  # Random 2x3 tensor
zeros = torch.zeros(2, 2)                  # 2x2 zero tensor
ones = torch.ones(2, 2)                    # 2x2 ones tensor

print("Matrix:\n", matrix)
print("Random:\n", random)


Matrix:
 tensor([[1, 2],
        [3, 4]])
Random:
 tensor([[0.5693, 0.4727, 0.3810],
        [0.5290, 0.9480, 0.0475]])
